import type { Metadata } from "next";
import RightSide from "./_components/RightSide";
import LeftSide from "./_components/LeftSide";

export const metadata: Metadata = {
  title: "Blog Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className={`mt-[7rem] flex flex-col md:grid grid-cols-8 w-full`}>
      <div className="col-span-2 hidden md:block">
        <div className="fixed  h-full top-0  left-0  md:w-[200px] lg:w-[250px] xl:w-[300px] 2xl:w-[400px] ">
          <LeftSide />
        </div>
      </div>
      <div className="col-span-4 ">{children}</div>
      <div className="col-span-2 hidden md:block">
        <div className="fixed  h-full top-0  right-0 md:w-[200px] lg:w-[250px] xl:w-[300px] 2xl:w-[400px] ">
          <RightSide />
        </div>
      </div>
    </main>
  );
}
