import type { Metadata } from "next";
import RightSide from "./_components/RightSide";
import LeftSide from "./_components/LeftSide";

export const metadata: Metadata = {
  title: "Blog Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className={`flex flex-col md:grid grid-cols-8 w-full mt-10`}>
      <div className="col-span-2 bg-green-500">
        <LeftSide />
      </div>
      <div className="col-span-4">{children}</div>
      <div className="col-span-2 bg-rose-500">
        <RightSide />
      </div>
    </main>
  );
}
